---
# tasks file for cassandra

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: cassandra

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: cassandra

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: cassandra
  
